### ISSUE TITLE
Validation addition - Feature request

### ISSUE THREAD

**Issue by VinayakSalunke** [PezzaD84/macOS-Patching-Upgrades#1]
Hi Perry @PezzaD84 ,
Could you please add a condition/validation in this script to check if MacBook got power source (power adapter) connected while this upgrade is in progress (it should be logged in logs too) would be really appreciated. 

Workflow would be like:   power source connected --> Yes ---> Continue to upgrade.
                                                                                      -->  No ---> give a popup to plug-in power adapter ---> validate power connection -->  if validation success--> continue upgrade --> if not successful --> halt the upgrade process and repeat popup until user plugs in the power source/adapter.

**Comment by PezzaD84** [comment]
All done. Luckily I had previously removed this so I had it ready to go back in.
